/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2019-06-25 12:26:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.news;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1559572009822L));
    _jspx_dependants.put("jar:file:/C:/Users/YOO/Downloads/board/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/piano/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/YOO/Downloads/board/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/piano/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>게시판 상세</title>\r\n");
    
    String boardSeq = request.getParameter("boardSeq");        

      out.write("\r\n");
      out.write(" \r\n");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f0_reused = false;
      try {
        _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f0.setParent(null);
        // /WEB-INF/views/news/boardDetail.jsp(13,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setVar("boardSeq");
        // /WEB-INF/views/news/boardDetail.jsp(13,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setValue(boardSeq);
        int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
        if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        _jspx_th_c_005fset_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
      }
      out.write(" <!-- 게시글 번호 -->\r\n");
      out.write("\r\n");
      out.write("<!-- 공통 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/resources/css/common/common.css\"/>\r\n");
      out.write(" \r\n");
      out.write("<!-- 공통 JavaScript -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/common/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("    $(document).ready(function(){        \r\n");
      out.write("        getBoardDetail();        \r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    /** 게시판 - 목록 페이지 이동 */\r\n");
      out.write("    function goBoardList(){                \r\n");
      out.write("        location.href = \"/news/boardList\";\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /** 게시판 - 수정 페이지 이동 */\r\n");
      out.write("    function goBoardUpdate(){\r\n");
      out.write("        \r\n");
      out.write("        var boardSeq = $(\"#board_seq\").val();\r\n");
      out.write("        \r\n");
      out.write("        location.href = \"/news/boardUpdate?boardSeq=\"+ boardSeq;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /** 게시판 - 답글 페이지 이동 */\r\n");
      out.write("\tfunction goBoardReply(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar boardSeq = $(\"#board_seq\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tlocation.href = \"/news/boardReply?boardSeq=\"+ boardSeq;\r\n");
      out.write("\t}\r\n");
      out.write("\t/** 게시판 - 첨부파일 다운로드 */\r\n");
      out.write("    function fileDownload(fileNameKey, fileName, filePath){\r\n");
      out.write("            \r\n");
      out.write("        location.href = \"/news/fileDownload?fileNameKey=\"+fileNameKey+\"&fileName=\"+fileName+\"&filePath=\"+filePath;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /** 게시판 - 상세 조회  */\r\n");
      out.write("    function getBoardDetail(boardSeq){\r\n");
      out.write("        \r\n");
      out.write("        var boardSeq = $(\"#board_seq\").val();\r\n");
      out.write(" \r\n");
      out.write("        if(boardSeq != \"\"){\r\n");
      out.write("            \r\n");
      out.write("            $.ajax({    \r\n");
      out.write("                \r\n");
      out.write("                url        : \"/news/getBoardDetail\",\r\n");
      out.write("                data    : $(\"#boardForm\").serialize(),\r\n");
      out.write("                dataType: \"JSON\",\r\n");
      out.write("                cache   : false,\r\n");
      out.write("                async   : true,\r\n");
      out.write("                type    : \"POST\",    \r\n");
      out.write("                success : function(obj) {\r\n");
      out.write("                    getBoardDetailCallback(obj);                \r\n");
      out.write("                },           \r\n");
      out.write("                error     : function(xhr, status, error) {}\r\n");
      out.write("                \r\n");
      out.write("             });\r\n");
      out.write("        } else {\r\n");
      out.write("            alert(\"오류가 발생했습니다.\\n관리자에게 문의하세요.\");\r\n");
      out.write("        }            \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /** 게시판 - 상세 조회  콜백 함수 */\r\n");
      out.write("    function getBoardDetailCallback(obj){\r\n");
      out.write("        \r\n");
      out.write("        var str = \"\";\r\n");
      out.write("        \r\n");
      out.write("        if(obj != null){                                \r\n");
      out.write("                            \r\n");
      out.write("            var boardSeq        = obj.board_seq; \r\n");
      out.write("            var boardReRef         = obj.board_re_ref; \r\n");
      out.write("            var boardReLev         = obj.board_re_lev; \r\n");
      out.write("            var boardReSeq         = obj.board_re_seq; \r\n");
      out.write("            var boardWriter     = obj.board_writer; \r\n");
      out.write("            var boardSubject     = obj.board_subject; \r\n");
      out.write("            var boardContent     = obj.board_content; \r\n");
      out.write("            var boardHits         = obj.board_hits;\r\n");
      out.write("            var delYn             = obj.del_yn; \r\n");
      out.write("            var insUserId         = obj.ins_user_id;\r\n");
      out.write("            var insDate         = obj.ins_date; \r\n");
      out.write("            var updUserId         = obj.upd_user_id;\r\n");
      out.write("            var updDate         = obj.upd_date;\r\n");
      out.write("            var files            = obj.files;        \r\n");
      out.write("            var filesLen        = files.length;\r\n");
      out.write("                        \r\n");
      out.write("            str += \"<tr>\";\r\n");
      out.write("            str += \"<th>제목</th>\";\r\n");
      out.write("            str += \"<td>\"+ boardSubject +\"</td>\";\r\n");
      out.write("            str += \"<th>조회수</th>\";\r\n");
      out.write("            str += \"<td>\"+ boardHits +\"</td>\";\r\n");
      out.write("            str += \"</tr>\";        \r\n");
      out.write("            str += \"<tr>\";\r\n");
      out.write("            str += \"<th>작성자</th>\";\r\n");
      out.write("            str += \"<td>\"+ boardWriter +\"</td>\";\r\n");
      out.write("            str += \"<th>작성일시</th>\";\r\n");
      out.write("            str += \"<td>\"+ insDate +\"</td>\";\r\n");
      out.write("            str += \"</tr>\";        \r\n");
      out.write("            str += \"<tr>\";\r\n");
      out.write("            str += \"<th>내용</th>\";\r\n");
      out.write("            str += \"<td colspan='3'>\"+ boardSubject +\"</td>\";\r\n");
      out.write("            str += \"</tr>\";\r\n");
      out.write("            \r\n");
      out.write("            if(filesLen > 0){\r\n");
      out.write("            \r\n");
      out.write("                for(var a=0; a<filesLen; a++){\r\n");
      out.write("                    \r\n");
      out.write("                    var boardSeq    = files[a].board_seq;\r\n");
      out.write("                    var fileNo         = files[a].file_no;\r\n");
      out.write("                    var fileNameKey = files[a].file_name_key;\r\n");
      out.write("                    var fileName     = files[a].file_name;\r\n");
      out.write("                    var filePath     = files[a].file_path;\r\n");
      out.write("                    var fileSize     = files[a].file_size;\r\n");
      out.write("                    var remark         = files[a].remark;\r\n");
      out.write("                    var delYn         = files[a].del_yn;\r\n");
      out.write("                    var insUserId     = files[a].ins_user_id;\r\n");
      out.write("                    var insDate     = files[a].ins_date;\r\n");
      out.write("                    var updUserId     = files[a].upd_user_id;\r\n");
      out.write("                    var updDate     = files[a].upd_date;\r\n");
      out.write("                    \r\n");
      out.write("                    console.log(\"fileName : \" + fileName);\r\n");
      out.write("                    \r\n");
      out.write("                    str += \"<th>첨부파일</th>\";\r\n");
      out.write("                    //str += \"<td onclick='javascript:fileDownload(\\\"\" + fileNameKey + \"\\\", \\\"\" + fileName + \"\\\", \\\"\" + filePath + \"\\\");' style='cursor:Pointer'>\"+ fileName +\"</td>\";\r\n");
      out.write("                    str += \"<td colspan='3'><img style='width:300px;height:300px' src=/resources/img/\"+fileNameKey+\"><a href='/news/fileDownload?fileNameKey=\"+encodeURI(fileNameKey)+\"&fileName=\"+encodeURI(fileName)+\"&filePath=\"+encodeURI(filePath)+\"'>\" + fileName + \"</a></td>\";\r\n");
      out.write("                    str += \"</tr>\";\r\n");
      out.write("                }    \r\n");
      out.write("            }            \r\n");
      out.write("            \r\n");
      out.write("        } else {\r\n");
      out.write("            \r\n");
      out.write("            alert(\"등록된 글이 존재하지 않습니다.\");\r\n");
      out.write("            return;\r\n");
      out.write("        }        \r\n");
      out.write("        \r\n");
      out.write("        $(\"#tbody\").html(str);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /** 게시판 - 삭제  */\r\n");
      out.write("    function deleteBoard(){\r\n");
      out.write(" \r\n");
      out.write("        var boardSeq = $(\"#board_seq\").val();\r\n");
      out.write("        \r\n");
      out.write("        var yn = confirm(\"게시글을 삭제하시겠습니까?\");        \r\n");
      out.write("        if(yn){\r\n");
      out.write("            \r\n");
      out.write("            $.ajax({    \r\n");
      out.write("                \r\n");
      out.write("                url        : \"/news/deleteBoard\",\r\n");
      out.write("                data    : $(\"#boardForm\").serialize(),\r\n");
      out.write("                dataType: \"JSON\",\r\n");
      out.write("                cache   : false,\r\n");
      out.write("                async   : true,\r\n");
      out.write("                type    : \"POST\",    \r\n");
      out.write("                success : function(obj) {\r\n");
      out.write("                    deleteBoardCallback(obj);                \r\n");
      out.write("                },           \r\n");
      out.write("                error     : function(xhr, status, error) {}\r\n");
      out.write("                \r\n");
      out.write("             });\r\n");
      out.write("        }        \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    /** 게시판 - 삭제 콜백 함수 */\r\n");
      out.write("    function deleteBoardCallback(obj){\r\n");
      out.write("    \r\n");
      out.write("        if(obj != null){        \r\n");
      out.write("            \r\n");
      out.write("            var result = obj.result;\r\n");
      out.write("            \r\n");
      out.write("            if(result == \"SUCCESS\"){                \r\n");
      out.write("                alert(\"게시글 삭제를 성공하였습니다.\");                \r\n");
      out.write("                goBoardList();                \r\n");
      out.write("            } else {                \r\n");
      out.write("                alert(\"게시글 삭제를 실패하였습니다.\");    \r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../main/header.jsp", out, true);
      out.write("\r\n");
      out.write("    <div id=\"container\">\r\n");
      out.write("        <div class=\"inner\">    \r\n");
      out.write("            <h2>게시글 상세</h2>\r\n");
      out.write("            <form id=\"boardForm\" name=\"boardForm\">        \r\n");
      out.write("                <table width=\"100%\" class=\"table01\">\r\n");
      out.write("                    <colgroup>\r\n");
      out.write("                        <col width=\"15%\">\r\n");
      out.write("                        <col width=\"35%\">\r\n");
      out.write("                        <col width=\"15%\">\r\n");
      out.write("                        <col width=\"*\">\r\n");
      out.write("                    </colgroup>\r\n");
      out.write("                    <tbody id=\"tbody\">\r\n");
      out.write("                       \r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>        \r\n");
      out.write("                <input type=\"hidden\" id=\"board_seq\"        name=\"board_seq\"    value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardSeq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/> <!-- 게시글 번호 -->\r\n");
      out.write("                <input type=\"hidden\" id=\"search_type\"    name=\"search_type\"     value=\"S\"/> <!-- 조회 타입 - 상세(S)/수정(U) -->\r\n");
      out.write("            </form>\r\n");
      out.write("            <div class=\"btn_right mt15\">\r\n");
      out.write("                <button type=\"button\" class=\"btn black mr5\" onclick=\"javascript:goBoardList();\">목록으로</button>\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("           \t\t<button type=\"button\" class=\"btn black mr5\" onclick=\"javascript:goBoardReply();\">답글쓰기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../main/footer.jsp", out, true);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/news/boardDetail.jsp(220,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo.get('uid') eq boardWriter}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <button type=\"button\" class=\"btn black mr5\" onclick=\"javascript:goBoardUpdate();\">수정하기</button>\r\n");
          out.write("                <button type=\"button\" class=\"btn black\" onclick=\"javascript:deleteBoard();\">삭제하기</button>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
